# Generated by Django 2.2 on 2019-04-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='zones',
            field=models.ManyToManyField(null=True, to='bus.Zone'),
        ),
    ]
